### ISSUE TITLE
How to define size-fraction-digits in parity system application? Why Instrument.java is not used in Parity System in Matching Engine

### ISSUE THREAD

**Issue by anujnetwork** [paritytrading/parity#116]
I see an option to define this in terminal client only.
How do i set this in Trading Engine

**Comment by anujnetwork** [comment]
Found the magic in client app

        Instrument config = instruments.get(instrument);

        String priceFormat = config.getPriceFormat();
        String sizeFormat  = config.getSizeFormat();

        String format = "%12s %16s %c %8s " + sizeFormat + " " + priceFormat;

        return String.format(LOCALE, format,
                Timestamps.format(timestamp / NANOS_PER_MILLI), orderId, side,
                ASCII.unpackLong(instrument), quantity / config.getSizeFactor(),
                price / config.getPriceFactor());

**Comment by anujnetwork** [comment]
Why Instrument.java is not used in Parity System in Matching Engine

**Comment by jvirtanen** [comment]
Why would you want to set it?

The matching engine solely operates on the minimum price and quantity increment because that is much simpler (integers as opposed to decimal numbers). Decimal digits are used purely for visual purposes in client applications.

You have opened 8 issues within 24 hours, most of which are not really issues but rather questions about the project. As you have noticed by closing some of these issues yourself, most of the things you can figure out just by reading the available documentation or thinking about the subject a bit more before reaching out for help.

I suggest using the [chat](https://gitter.im/paritytrading/chat) for these kind of questions from now on.
