### ISSUE TITLE
Hi @jvirtanen , How to close connection code wise without terminal client terminates.

### ISSUE THREAD

**Issue by imrozoodles** [paritytrading/parity#124]
_Originally posted by @imrozoodles in https://github.com/paritytrading/parity/issue_comments#issuecomment-427249233_

**Comment by jvirtanen** [comment]
Just close the TCP connection. How exactly to do it depends on which programming language and libraries you are using. If you are using the reference implementation, a good starting point is to look at the basics of [Java NIO](https://en.wikipedia.org/wiki/Non-blocking_I/O_(Java)) and [the Nassau API](http://api.paritytrading.com/nassau/latest/).

I suggest asking these kind of general questions on [the Gitter chat](https://gitter.im/paritytrading/chat) instead of opening GitHub issues.
